postgresql:
  host: 127.0.0.1
  port: 5432
  username: postgres
  database: nagato
  password: root
  timezone: Asia/Shanghai

mongo:
  uri: 127.0.0.1:27017
  database: 

redis:
  host: 127.0.0.1
  port: 6379

rabbitmq:
  username: harukaze
  password: 123456
  host: 127.0.0.1
  port: 5672

server:
  host: 127.0.0.1
  port: 10000

services: 
  - nagato.search

etcd:
  host: 127.0.0.1
  port: 2379